name: Push Updates

on:
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get Versions
        id: script
        run: python3 dev/versionchecker.py

    outputs:
      matrix: ${{ steps.script.outputs.matrix }}

  build-versions:
    needs: get-versions
    if: ${{ fromJSON(needs.get-versions.outputs.matrix).include[0] != null }}
    strategy:
      matrix: ${{ fromJSON(needs.get-versions.outputs.matrix) }}

    permissions:
      contents: read
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-build-push.yml@main
    with:
      platform: linux/amd64
      tags: ${{ matrix.tags }}
      context: docker
      dockerfile: ${{ matrix.dockerfile }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
